[project]
name = "murd3r-b4t"
version = "0.1.0"
description = ""
authors = [
    {name = "Monish Giani.",email = "256585194+thelazybastard@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest (>=9.1.1,<10.0.0)",
    "black (>=26.10.0,<27.0.0)",
    "mypy (>=2.4.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "murd3r_b4t", from = "src"}]

[tool.poetry.scripts]
bot = "murd3r_b4t.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
